### PR TITLE
Add docker.io apt package to install.

### PR DESCRIPTION
**Pull request by junaruga**
Because I want to add a test case to run container in the container (docker in docker) in CI.

You can see https://github.com/ruby/ruby/pull/5900 for detail.

### CODE REVIEW

**Comment by hsbt** [comment]
I'm not sure the package detail of `docker` in ubuntu. Is it only CLI binaries?

**Comment by junaruga** [comment]
Thanks for your review. Good point. Let me check the detail.

**Comment by junaruga** [comment]
Sorry the `docker` page was wrong,  and the `docker.io` package contains the docker command. https://packages.ubuntu.com/focal/amd64/docker.io/filelist .

However when I tested the containers on my forked repo, https://github.com/users/junaruga/packages/container/package/ruby-ci-image, I noticed that it is not enough. I need to add a logic to run docker in docker. So, I will investigate it.

```
$ docker run --rm -it ghcr.io/junaruga/ruby-ci-image:gcc-11 bash

ci@34ab44fd1cc1:/$ docker -v
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1

$ docker run --rm -it docker.io/fedora:latest bash
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'

ci@34ab44fd1cc1:/$ sudo service docker status
docker: unrecognized service

ci@34ab44fd1cc1:/$ sudo systemctl status docker
sudo: systemctl: command not found
```

**Comment by junaruga** [comment]
It seems that docker in docker works on ruby/ruby GitHub Actions, just adding `docker.io` apt package. I am testing it on it on my forked repo.

**Comment by junaruga** [comment]
The PR https://github.com/ruby/ruby/pull/5900 passed with containers by this PR. Can I merge this PR first?

**Review by shyouhei — APPROVED** [review]
Looks good to me.

**Comment by junaruga** [comment]
Thanks for your review! Merged.

**Pull request merged**
